---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    purpose: roboshop
    component: mongodb
    tier: db
  namespace: roboshop
spec:
  # Specify replicas to be created
  replicas: 1
  selector:
    matchLabels:
      purpose: roboshop
      component: mongodb
      tier: db
  template:
    # pod definition
    metadata:
      labels:
        purpose: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion }}"
          imagePullPolicy: Always
          readinessProbe: # check if application is ready to serve requests
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe: # check if application is alive or not.
            tcpSocket:
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 5
