---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  type: "{{ .Values.service.type }}""
  selector:
    purpose: roboshop
    component: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017