---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    purpose: roboshop
    component: user
    tier: backend
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    purpose: roboshop
    component: user
    tier: backend
  namespace: roboshop
spec:
  # Specify replicas to be created
  replicas: 1
  selector:
    matchLabels:
      purpose: roboshop
      component: user
      tier: backend
  template:
    # pod definition
    metadata:
      labels:
        purpose: roboshop
        component: user
        tier: backend
    spec:
      containers:
        - name: user
          image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: user
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: liveness-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 15
