---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  type: "{{ .Values.service.type }}"
  selector:
    purpose: roboshop
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306 #  servicePort
      targetPort: 3306 #  containerPort
