---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  type: "{{ .Values.service.type }}"
  selector:
    purpose: roboshop
    component: redis
    tier: db
  ports:
    - protocol: TCP
      port: 6379 #  servicePort
      targetPort: 6379 #  containerPort
