---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    purpose: roboshop
    component: cart
    tier: backend
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    purpose: roboshop
    component: cart
    tier: backend
  namespace: roboshop
spec:
  # Specify replicas to be created
  replicas: 1
  selector:
    matchLabels:
      purpose: roboshop
      component: cart
      tier: backend
  template:
    # pod definition
    metadata:
      labels:
        purpose: roboshop
        component: cart
        tier: backend
    spec:
      containers:
        - name: cart
          image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cart
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: liveness-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 15
