---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: "{{ .Values.service.type }}"
  selector:
    purpose: roboshop
    component: frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80 #servicePort
      targetPort: 8080 #containerPort
